image: docker:18.09

stages:
  - build-package-gradle
  - build-image
  - deploy-package-gradle

build-package-gradle 1/1:
  image: alpine/java:21-jdk
  stage: build-package-gradle
  before_script:
    - chmod 777 ./gradlew
  script:
    - echo [INFO] gradle build시작
    - ./gradlew build
  only:
    - main
    - dev
    - merge_requests
    - /^feat\/.*$/ # 특정 브랜치 패턴에서 실행

deploy-package-gradle 1/2:
  stage: build-image
  image: gcr.io/kaniko-project/executor:latest
  script:
    - docker build -t my-demo:$CI_COMMIT_REF_NAME .
    - docker push my-demo:$CI_COMMIT_REF_NAME

deploy-package-gradle 2/2:
  stage: deploy-package-gradle
  when: on_success
  script:
    - kubectl create ns my-demo:$CI_COMMIT_REF_NAME
    - kubectl apply -f deployment.yaml -n my-demo:$CI_COMMIT_REF_NAME
  only:
    - main
    - dev
    - merge_requests
    - /^feat\/.*$/ # 특정 브랜치 패턴에서 실행
